### ISSUE TITLE
Non fungible position manager

### ISSUE THREAD

**Issue by cryptoshan12** [Uniswap/v3-periphery#285]
This error is showing when I'm trying to add position in liquidity pair.

I deployed NONFUNGIBLE_POSITION_MANAGER contract by copying openzeppelin files from uniswap original contract to root directory because openzeppelin updated there version and deleted old version files.

When i change back NONFUNGIBLE_POSITION_MANAGER_ADDRESSES to its default everything works fine.

Please help me in this.

index.js:1 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"code":-32000,"message":"execution reverted"}, method="estimateGas", transaction={"from":"0x1F193EA5B34f964871CB9645277354f51c3ff18B","to":"0xe98C7E73e3f4cA85277BE520307F73b962C06287","value":{"type":"BigNumber","hex":"0x01d133e1ac94def3"},"data":"0xac9650d800000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000164883164560000000000000000000000001f9840a85d5af5bf1d1762f925bdaddc4201f984000000000000000000000000c778417e063141139fce010982780140aa0cd5ab0000000000000000000000000000000000000000000000000000000000000bb8fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2764c00000000000000000000000000000000000000000000000000000000000d89b4000000000000000000000000000000000000000000000000020ed78c912108af00000000000000000000000000000000000000000000000001d133e1ac94def3000000000000000000000000000000000000000000000000020ed78c912108af00000000000000000000000000000000000000000000000001d133e1ac94def30000000000000000000000001f193ea5b34f964871cb9645277354f51c3ff18b0000000000000000000000000000000000000000000000000000000062c789ef00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000412210e8a00000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.2)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at checkError (json-rpc-provider.ts:108:1)
    at Web3Provider.<anonymous> (json-rpc-provider.ts:590:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.ts:2:1)

**Comment by leon-do** [comment]
did you find a solution to this?
